#---------------------------------------#
# File:     reverse.py                  #
# Version:  0.0.1                       #
# Author:   Michael Carpenter           #
# Date:     13/2/13                     #
#---------------------------------------#
import re

original  = "AATAATTATTCGACTTGAACTCGGTTCATGTAATAGTTTAATTAATAATGATCAAATCTATAACTCAATAGTAACAAGACATGCCTTCATCATAATTTTTTTTATGGTTATACCCTTTATAATTGGCGGGTTCGGTAATTTTCTTGTCCCATTAATACTCGGAACCCCCGATATAGCATTCCCACGAATAAATAATATAAGATTTTGACTCCTCCCACCATCAATCTCCTTATTAATTTTAAGAAACTTTATTGGAAGGGGTGTCGGAACTGGATGAACTATTTATCCTCCTCTTGCCTCAAATATTTTTCATAGAGGCCCCTCAGTTGATATATCTATTTTCTCATTACATATTGCTGGAATATCATCAATTCTCGGAGCTATTAATTTTATTACTACAATTTTAAATATACATCACATAAACTTTACTATAGATAAAATTCCTCTCTTAGTATGATCTATTCTTATTACAGCAGTACTTTTATTATTGTCTCTCCCAGTTCTCGCTGGGGCAATTACTATACTATTAACTGATCGAAACTTAAATACCACTTTTTTTGATCCAAGAGGAGGTGGAGATCCTATTTTATATCAACATTTATTTTGATTTTTTGGTCACC"

complement  = " "

bioeditcomp = "GGTGACCAAAAAATCAAAATAAATGTTGATATAAAATAGGATCTCCACCTCCTCTTGGATCAAAAAAAGTGGTATTTAAGTTTCGATCAGTTAATAGTATAGTAATTGCCCCAGCGAGAACTGGGAGAGACAATAATAAAAGTACTGCTGTAATAAGAATAGATCATACTAAGAGAGGAATTTTATCTATAGTAAAGTTTATGTGATGTATATTTAAAATTGTAGTAATAAAATTAATAGCTCCGAGAATTGATGATATTCCAGCAATATGTAATGAGAAAATAGATATATCAACTGAGGGGCCTCTATGAAAAATATTTGAGGCAAGAGGAGGATAAATAGTTCATCCAGTTCCGACACCCCTTCCAATAAAGTTTCTTAAAATTAATAAGGAGATTGATGGTGGGAGGAGTCAAAATCTTATATTATTTATTCGTGGGAATGCTATATCGGGGGTTCCGAGTATTAATGGGACAAGAAAATTACCGAACCCGCCAATTATAAAGGGTATAACCATAAAAAAAATTATGATGAAGGCATGTCTTGTTACTATTGAGTTATAGATTTGATCATTATTAATTAAACTATTACATGAACCGAGTTCAAGTCGAATAATTATT"

complement  = original[::-1]
complement  = complement.replace('A','1').replace('T','2').replace('G','3').replace('C','4')
complement  = complement.replace('1','T').replace('2','A').replace('3','C').replace('4','G')

print "-----------------------------------------------"
print "Original Sequence: \t\t", original
print "Reverse Complement Sequence: \t", complement
print "Bioedit Version: \t\t", bioeditcomp

errors=0
if complement == bioeditcomp:
  print "Got an A!"
else:
  print "Nope! Not yet"

  for i,j in zip(complement,bioeditcomp):
    if i!=j:
      error+=1

print "Number of differences:",errors
print "Percent difference:",float(errors)/len(complement)*100
print "-----------------------------------------------"

